import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex justify-between w-full px-10 py-4">
          <div id="brand" className="text-2xl text-teal-400 font-mono uppercase">
            Logo
          </div>
          <div id="navigation-bar" className="flex">
            <div className="px-4">About</div>
            <div className="px-4">Guiding</div>
            <div className="px-4">Enquire</div>
          </div>
        </header>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
